### ISSUE TITLE
ENOENT error for "append  vendor/assets/javascripts/spree/frontend/all.js"

### ISSUE THREAD

**Issue by kk009** [shoppingin/sumie#2]
I am installing this extension on an existing spree setup. Spree version is 3.0.10. Please find stack trace here after running "rails g sumie:install" command:

```
append  vendor/assets/javascripts/spree/frontend/all.js
/Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions/inject_into_file.rb:95:in `binread': No such file or directory @ rb_sysopen - /Users/kaustubh/Desktop/Workspace/Samples/spree_suppliers/vendor/assets/javascripts/spree/frontend/all.js (Errno::ENOENT)
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions/inject_into_file.rb:95:in `replace!'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions/inject_into_file.rb:56:in `invoke!'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions.rb:95:in `action'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions/inject_into_file.rb:27:in `insert_into_file'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/actions/file_manipulation.rb:180:in `append_to_file'
	from /Users/kaustubh/Desktop/Workspace/Samples/spree_suppliers/lib/generators/sumie/install/install_generator.rb:8:in `add_javascripts'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/generators.rb:157:in `invoke'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/commands/generate.rb:13:in `<top (required)>'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/gems/railties-4.2.7.1/lib/rails/engine/commands.rb:19:in `<top (required)>'
	from /Users/kaustubh/Desktop/Workspace/Samples/spree_suppliers/bin/rails:7:in `require'
	from /Users/kaustubh/Desktop/Workspace/Samples/spree_suppliers/bin/rails:7:in `<top (required)>'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/bin/rails:22:in `load'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/bin/rails:22:in `<main>'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/kaustubh/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

@Funfun Any idea ?

**Comment by tsyber1an** [comment]
@kk009 i stopped support of this extension.
